### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by sukima**
@sukima can you please enable Travis CI for this repo? I've had my colleague @Mawaheb raise a PR for tests (#9) and I'll like to plug them into continuous integration.

I've checked an only the repo owner can enable Travis. I will take care of the Travis CI configuration, all we need is for you to login to Travis and hit the "on" switch.

### CODE REVIEW

**Comment by sukima** [comment]
On it...

**Comment by sukima** [comment]
FYI, I upgraded Ember-CLI and pushed version 1.2.0 (Tests passed when I did).

**Comment by johnnyshields** [comment]
@Mawaheb can you look into getting to creating a `.travis.yml` that works for this repo? You can go to https://travis-ci.org/, create an account linked to your Github, then activate your fork of this repo.

Once you push a `.travis.yml` to the root of your fork, Travis should see the tests and run automatically.

Here are some examples that seem to be working for other Ember addons, looks like Travis uses node to run:
- https://github.com/dockyard/ember-in-viewport/blob/develop/.travis.yml
- https://github.com/williamsbdev/ember-cli-focus-input/blob/master/.travis.yml

**Comment by sukima** [comment]
Unfortunately commit a214f81 broke tests. Looking into it.

**Comment by sukima** [comment]
Looking at this. unit tests don't use an ember app and so don't render to the dom. What this means is the 'it renders' tests need to be managed in integration tests which use `module` and the said `beforeEach` / `afterEach` methods while the unit tests use the `moduleForComponent` helper which doesn't play nice with `startApp`.

**Comment by sukima** [comment]
I'm working on fixing the test but my :train: ride is almost over. I'll get to this tonight or tomorrow morning. Ok?

**Comment by johnnyshields** [comment]
Sure not urgent!

**Comment by johnnyshields** [comment]
Oops I just committed Travis badge to master already. There's gonna be a conflict in README.md. Sorry about that.

**Comment by sukima** [comment]
No worries, I'm a git-fu master at conflict resolution :grin:

**Comment by sukima** [comment]
Finally code works

**Comment by sukima** [comment]
So I'm merging this for now. I think there is a lot of head way and with an establish pattern for both unit and integration tests we can add more easily later. It get's better from here.

**Comment by johnnyshields** [comment]
@sukima awesome work. Thanks so much this is great.

**Pull request merged**
