### PR TITLE
Add a keyboard-select-picker

### PR DESCRIPTION
**Pull request by sukima**
Same as the select-picker but with keyboard support for selecting items.

### CODE REVIEW

**Comment by sukima** [comment]
I have another branch to add tests but they break because the ember-keyboard-shortcuts addon hasn't been updated for Ember-CLI 0.2.3 yet. When it does I can merge in the test suite for this component. I have dev tested it so I'm feeling pretty good about it.

I'm planning on merging this. @johnnyshields, @arkadiyk, @Mawaheb does anyone have any objections?!

**Comment by johnnyshields** [comment]
Why not make keyboard support standard on all select pickers, with a flag to disable? don't see why it should be a separate component.

**Comment by sukima** [comment]
Needs to be separate because the keyboard support is dependent on another addon that I didn't want to force on users. That way if they don't include the ember-keyboard-shortcuts addon then they can skip it. Because of how ES6 works you _must_ have the component in `node_modules` or else. Hence two different code paths.

**Comment by sukima** [comment]
Addendum: I experimented with having nested add on dependencies and found that Ember-CLI has difficulties with that. It was easier to just tell users to install `ember-keyboard-shortcut` manually.

**Comment by johnnyshields** [comment]
One way to do this might be to have users include ember-keyboard-shortcut externally (not in this plugin), and add it only as a devDependency. Then we can detect for it's presence, and "upgrade" the functionality of the select picker if it's present. (Not sure if you can actually do this NPM, I do it in Ruby a lot.)

**Comment by sukima** [comment]
@johnnyshields That was my first try. Unfortunately the ES6 to 5 transpiler (bable) does not let you perform conditional `import` statements. Apparently this is part of the ES6 spec? This means there is no way of performing the needed import to get the mixin without putting it into the select-picker source. But once you do that it will blow up if the user hasn't installed the required dependency. Can't wrap the statement in a try/catch block because that's a ES6 syntax error. So the only way I could find was to have a keyboard-select-picker component that does use the proper import statement and as long as a user doesn't attempt to use that component then everything is fine. It's only when they use that component do they also need to install the needed dependency.

This is one of the core reasons I get so frustrated with the ES6 mentality when CommonJS (Node's require concept) worked so well and you **could** do conditional dependencies.

Unless I'm missing something this was the only method I could think of to accomplish all my goals.

Anyway, I'm going to merge this and if anyone can come up with a better methodology just let me know and I'll be happy to refactor it.

**Comment by johnnyshields** [comment]
Sounds good to me, let's merge.

**Pull request merged**
